language: julia
os:
  - linux
julia:
  - 0.7
  - 1.0

matrix:
  fast_finish: true
  allow_failures:
    - julia: 1.0

notifications:
  email: false
addons:
    apt_packages:
        - gfortran
after_success:
  - julia -e 'import Pkg; cd(Pkg.dir("SVDD")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())';
